// src/components/GisExportPanel.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Download, FileJson, Focus, Image, RotateCcw, Upload } from 'lucide-vue-next'
import { convertGeoJson, parseGeoJson, sampleGeoJson } from '../lib/geojson'
import type { MapExportProgress, MapRuntime } from '../lib/map-runtime'
import type { MapWorkspaceController } from '../composables/useMapWorkspace'

const props = defineProps<{ runtime: MapRuntime; workspace: MapWorkspaceController }>()

const fileInput = ref<HTMLInputElement>()
const fileName = ref('')
const hasSelection = ref(false)
const selecting = ref(false)
const exporting = ref(false)
const exportZoom = ref(Math.min(20, Math.max(3, Math.ceil(props.runtime.map.getZoom()) + 2)))
const progress = ref<MapExportProgress | null>(null)
const status = ref('')
const error = ref('')

function renderSample() {
  props.workspace.replaceCollection(sampleGeoJson)
  fileName.value = 'demo.geojson'
  error.value = ''
}

async function loadFile(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (!file) return
  try {
    const data = parseGeoJson(await file.text())
    props.workspace.replaceCollection(convertGeoJson(data, props.workspace.snapshot.value.sourceCrs, 'wgs84'))
    fileName.value = file.name
    error.value = ''
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'The file could not be read.'
  } finally {
    ;(event.target as HTMLInputElement).value = ''
  }
}

async function selectRegion() {
  selecting.value = true
  status.value = 'Draw a rectangle on the map'
  try {
    await props.runtime.startRectangle()
    hasSelection.value = true
    status.value = 'Region selected'
  } catch (reason) {
    if (!(reason instanceof DOMException && reason.name === 'AbortError')) {
      error.value = reason instanceof Error ? reason.message : 'Region selection failed.'
    }
    status.value = ''
  } finally {
    selecting.value = false
  }
}

function resetSelection() {
  props.runtime.clearRectangle()
  hasSelection.value = false
  status.value = ''
}

async function exportMap(selectionOnly: boolean) {
  exporting.value = true
  progress.value = null
  error.value = ''
  try {
    await props.runtime.exportPng({
      selectionOnly,
      zoom: exportZoom.value,
      onProgress: (value) => (progress.value = value),
    })
    status.value = 'PNG downloaded'
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'PNG export failed.'
  } finally {
    exporting.value = false
  }
}

function clearData() {
  props.workspace.clear()
  fileName.value = ''
}
</script>

<template>
  <div class="panel-scroll">
    <section class="tool-section">
      <h2>GeoJSON data</h2>
      <input ref="fileInput" class="visually-hidden" type="file" accept=".json,.geojson,application/geo+json" @change="loadFile" />
      <div class="button-grid">
        <button class="button primary" type="button" @click="fileInput?.click()">
          <Upload :size="16" /> Import file
        </button>
        <button class="button secondary" type="button" @click="renderSample">
          <FileJson :size="16" /> Demo data
        </button>
      </div>
      <div v-if="fileName" class="file-summary">
        <FileJson :size="18" />
        <div><strong>{{ fileName }}</strong><span>{{ workspace.snapshot.value.collection.features.length }} features</span></div>
        <button class="icon-button" type="button" title="Clear data" @click="clearData"><RotateCcw :size="16" /></button>
      </div>
    </section>

    <section class="tool-section">
      <h2>Export area</h2>
      <div class="button-grid">
        <button class="button secondary" type="button" :disabled="selecting" @click="selectRegion">
          <Focus :size="16" /> {{ selecting ? 'Drawing...' : 'Select region' }}
        </button>
        <button class="button secondary" type="button" :disabled="!hasSelection" @click="resetSelection">
          <RotateCcw :size="16" /> Reset
        </button>
      </div>
      <p v-if="status" class="status-line">{{ status }}</p>
    </section>

    <section class="tool-section">
      <h2>PNG output</h2>
      <label class="field-label" for="export-zoom">Detail zoom</label>
      <input id="export-zoom" v-model.number="exportZoom" type="number" min="3" max="20" step="1" :disabled="exporting" />
      <div class="export-actions">
        <button class="button primary" type="button" :disabled="exporting" @click="exportMap(false)">
          <Image :size="16" /> Current view
        </button>
        <button class="button primary" type="button" :disabled="exporting || !hasSelection" @click="exportMap(true)">
          <Download :size="16" /> Selected region
        </button>
      </div>
      <div v-if="progress" class="export-progress">
        <progress :value="progress.completed" :max="progress.total" />
        <div>
          <span>{{ progress.phase === 'capturing' ? 'Capturing' : 'Merging' }} {{ progress.completed }} / {{ progress.total }}</span>
          <span>{{ progress.width }} x {{ progress.height }} px</span>
        </div>
      </div>
      <p v-if="error" class="inline-error" role="alert">{{ error }}</p>
    </section>
  </div>
</template>

// src/components/GisExportPanel.tsx
import { Download, FileJson, Focus, Image, RotateCcw, Upload } from 'lucide-react'
import { type ChangeEvent, useRef, useState } from 'react'
import type { MapWorkspaceController } from '../hooks/useMapWorkspace'
import { convertGeoJson, parseGeoJson, sampleGeoJson } from '../lib/geojson'
import type { MapExportProgress, MapRuntime } from '../lib/map-runtime'

interface GisExportPanelProps {
  runtime: MapRuntime
  workspace: MapWorkspaceController
}

export default function GisExportPanel({ runtime, workspace }: GisExportPanelProps) {
  const fileInput = useRef<HTMLInputElement>(null)
  const [fileName, setFileName] = useState('')
  const [hasSelection, setHasSelection] = useState(false)
  const [selecting, setSelecting] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [exportZoom, setExportZoom] = useState(Math.min(20, Math.max(3, Math.ceil(runtime.map.getZoom()) + 2)))
  const [progress, setProgress] = useState<MapExportProgress | null>(null)
  const [status, setStatus] = useState('')
  const [error, setError] = useState('')

  const renderSample = (): void => {
    workspace.replaceCollection(sampleGeoJson)
    setFileName('demo.geojson')
    setError('')
  }

  const loadFile = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = event.target.files?.[0]
    if (!file) return
    try {
      const data = parseGeoJson(await file.text())
      workspace.replaceCollection(convertGeoJson(data, workspace.snapshot.sourceCrs, 'wgs84'))
      setFileName(file.name)
      setError('')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'The file could not be read.')
    } finally {
      event.target.value = ''
    }
  }

  const selectRegion = async (): Promise<void> => {
    setSelecting(true)
    setStatus('Draw a rectangle on the map')
    try {
      await runtime.startRectangle()
      setHasSelection(true)
      setStatus('Region selected')
    } catch (reason) {
      if (!(reason instanceof DOMException && reason.name === 'AbortError')) {
        setError(reason instanceof Error ? reason.message : 'Region selection failed.')
      }
      setStatus('')
    } finally {
      setSelecting(false)
    }
  }

  const resetSelection = (): void => {
    runtime.clearRectangle()
    setHasSelection(false)
    setStatus('')
  }

  const exportMap = async (selectionOnly: boolean): Promise<void> => {
    setExporting(true)
    setProgress(null)
    setError('')
    try {
      await runtime.exportPng({ selectionOnly, zoom: exportZoom, onProgress: setProgress })
      setStatus('PNG downloaded')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'PNG export failed.')
    } finally {
      setExporting(false)
    }
  }

  const clearData = (): void => {
    workspace.clear()
    setFileName('')
  }

  return (
    <div className="panel-scroll">
      <section className="tool-section">
        <h2>GeoJSON data</h2>
        <input ref={fileInput} className="visually-hidden" type="file" accept=".json,.geojson,application/geo+json" onChange={(event) => void loadFile(event)} />
        <div className="button-grid">
          <button className="button primary" type="button" onClick={() => fileInput.current?.click()}><Upload size={16} /> Import file</button>
          <button className="button secondary" type="button" onClick={renderSample}><FileJson size={16} /> Demo data</button>
        </div>
        {fileName && (
          <div className="file-summary">
            <FileJson size={18} />
            <div><strong>{fileName}</strong><span>{workspace.snapshot.collection.features.length} features</span></div>
            <button className="icon-button" type="button" title="Clear data" onClick={clearData}><RotateCcw size={16} /></button>
          </div>
        )}
      </section>

      <section className="tool-section">
        <h2>Export area</h2>
        <div className="button-grid">
          <button className="button secondary" type="button" disabled={selecting} onClick={() => void selectRegion()}><Focus size={16} /> {selecting ? 'Drawing...' : 'Select region'}</button>
          <button className="button secondary" type="button" disabled={!hasSelection} onClick={resetSelection}><RotateCcw size={16} /> Reset</button>
        </div>
        {status && <p className="status-line">{status}</p>}
      </section>

      <section className="tool-section">
        <h2>PNG output</h2>
        <label className="field-label" htmlFor="export-zoom">Detail zoom</label>
        <input id="export-zoom" value={exportZoom} onChange={(event) => setExportZoom(Number(event.target.value))} type="number" min="3" max="20" step="1" disabled={exporting} />
        <div className="export-actions">
          <button className="button primary" type="button" disabled={exporting} onClick={() => void exportMap(false)}><Image size={16} /> Current view</button>
          <button className="button primary" type="button" disabled={exporting || !hasSelection} onClick={() => void exportMap(true)}><Download size={16} /> Selected region</button>
        </div>
        {progress && (
          <div className="export-progress">
            <progress value={progress.completed} max={progress.total} />
            <div>
              <span>{progress.phase === 'capturing' ? 'Capturing' : 'Merging'} {progress.completed} / {progress.total}</span>
              <span>{progress.width} x {progress.height} px</span>
            </div>
          </div>
        )}
        {error && <p className="inline-error" role="alert">{error}</p>}
      </section>
    </div>
  )
}
