// src/components/MapViewport.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { LoaderCircle, TriangleAlert } from 'lucide-vue-next'
import type { AMapCredentials } from '../lib/credentials'
import { createMapRuntime, type MapRuntime } from '../lib/map-runtime'

const props = defineProps<{ credentials?: AMapCredentials | null }>()
const emit = defineEmits<{ ready: [runtime: MapRuntime]; error: [message: string] }>()

const container = ref<HTMLElement>()
const loading = ref(true)
const error = ref('')
let runtime: MapRuntime | undefined

onMounted(async () => {
  try {
    runtime = await createMapRuntime(container.value!, props.credentials)
    emit('ready', runtime)
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'The maptalks map could not be loaded.'
    emit('error', error.value)
  } finally {
    loading.value = false
  }
})

onBeforeUnmount(() => runtime?.destroy())
</script>

<template>
  <div ref="container" class="map-canvas" aria-label="maptalks map canvas" />
  <div v-if="loading" class="map-state">
    <LoaderCircle class="spin" :size="22" />
    <span>Loading map</span>
  </div>
  <div v-else-if="error" class="map-state error-state">
    <TriangleAlert :size="22" />
    <span>{{ error }}</span>
  </div>
</template>

// src/components/MapViewport.tsx
import { LoaderCircle, TriangleAlert } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { AMapCredentials } from '../lib/credentials'
import { createMapRuntime, type MapRuntime } from '../lib/map-runtime'

interface MapViewportProps {
  credentials?: AMapCredentials | null
  onReady: (runtime: MapRuntime) => void
  onError: (message: string) => void
}

export default function MapViewport({ credentials, onReady, onError }: MapViewportProps) {
  const container = useRef<HTMLDivElement>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    let disposed = false
    let runtime: MapRuntime | undefined
    setLoading(true)
    setError('')

    const initialize = (): void => {
      try {
        if (!container.current) return
        const nextRuntime = createMapRuntime(container.current, credentials)
        runtime = nextRuntime
        onReady(nextRuntime)
      } catch (reason) {
        if (disposed) return
        const message = reason instanceof Error ? reason.message : 'The maptalks map could not be loaded.'
        setError(message)
        onError(message)
      } finally {
        if (!disposed) setLoading(false)
      }
    }

    initialize()
    return () => {
      disposed = true
      runtime?.destroy()
    }
  }, [credentials, onError, onReady])

  return (
    <>
      <div ref={container} className="map-canvas" aria-label="maptalks map canvas" />
      {loading && (
        <div className="map-state"><LoaderCircle className="spin" size={22} /><span>Loading map</span></div>
      )}
      {!loading && error && (
        <div className="map-state error-state"><TriangleAlert size={22} /><span>{error}</span></div>
      )}
    </>
  )
}
